topics:
  - name: joy
    topic: joy_teleop/cmd_vel
    timeout: 0.5
    priority: 100
  - name: tablet
    topic: tablet_teleop/cmd_vel
    timeout: 0.5
    priority: 90
  - name: interactive_marker
    topic: diff_drive_marker/cmd_vel
    timeout: 0.5
    priority: 20
  - name: nav
    topic: nav/cmd_vel
    timeout: 0.5
    priority: 10
locks:
  - name: e_stop
    topic: e_stop
    timeout: 0.0
    priority: 255
